# Generated by Django 4.2.16 on 2024-09-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_barbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.barbers'),
        ),
    ]
