# Generated by Django 4.2.16 on 2024-09-20 21:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_booking_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barber_shops/')),
                ('cover_image', models.ImageField(upload_to='barber_shops/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='barber',
            name='barber_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='scheduler.barbershop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='barber_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduler.barbershop'),
        ),
        migrations.AddField(
            model_name='service',
            name='barber_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scheduler.barbershop'),
        ),
        migrations.AddField(
            model_name='shift',
            name='barber_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduler.barbershop'),
        ),
        migrations.AddField(
            model_name='slot',
            name='barber_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.barbershop'),
        ),
    ]
